---
shallow_clone: true
platform: x64
install:
  - SET
  - '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64'
  - SET PATH=\usr\local\bin;C:\Ruby22-x64\bin;C:\Ruby21-x64\Devkit\mingw\bin;%PATH%;C:\msys64\usr\bin
  - ruby --version
  - 'cl'
  - SET
  - ps: Start-FileDownload 'http://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.2.5-windows.zip'
  - 7z x libressl-2.2.5-windows.zip
  - copy libressl-2.2.5-windows\x64\libcrypto-35.lib libressl-2.2.5-windows\x64\crypto.lib
  - copy libressl-2.2.5-windows\x64\libssl-35.lib    libressl-2.2.5-windows\x64\ssl.lib
  - mkdir \usr\local\bin
  - copy libressl-2.2.5-windows\x64\libcrypto-35.dll \usr\local\bin
  - copy libressl-2.2.5-windows\x64\libssl-35.dll    \usr\local\bin
  - ps: Start-FileDownload 'http://zlib.net/zlib128.zip'
  - 7z x zlib128.zip
  - cd zlib-1.2.8
  - nmake -f win32/Makefile.msc
  - copy zlib1.dll ..
  - copy zlib1.dll \usr\local\bin
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - win32\configure.bat --without-tk --with-openssl-include=/projects/%APPVEYOR_PROJECT_SLUG%/libressl-2.2.5-windows/include --with-openssl-lib=/projects/%APPVEYOR_PROJECT_SLUG%/libressl-2.2.5-windows/x64 --with-zlib-include=/projects/%APPVEYOR_PROJECT_SLUG%/zlib-1.2.8 --with-zlib-lib=/projects/%APPVEYOR_PROJECT_SLUG%/zlib-1.2.8
  - nmake -l up
  - nmake -l
  - nmake install-nodoc
test_script:
  - nmake -l "OPTS=-v -q" btest
  - nmake -l "OPTS=-v -q" test-basic
